version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestControlsProject
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: testControlsFromOnPrem_Render_1
  gitServerName: test
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
